export enum CubeType {
  ALL = '',
  ClassRoomLecture = 'ClassRoomLecture',
  ELearning = 'ELearning',
  Video = 'Video',
  Audio = 'Audio',
  Documents = 'Documents',
  Experiential = 'Experiential',
  WebPage = 'WebPage',
  Community = 'Community',
  Task = 'Task',
  Cohort = 'Cohort',
  Discussion = 'Discussion',
  Empty = '',
}
