### Get Menu
GET http://localhost:8080/773613/menus
audienceId: r36x-r@ne1-m2-c2
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhZGRpdGlvbmFsSW5mb3JtYXRpb24iOnsiY29tcGFueUNvZGUiOiJTS0NDIiwiZW1wbG95ZWVJZCI6IjA3NzY2In0sImxvZ2luSWQiOiJTS0NDLjA3NzY2QHNrLmNvbSIsInVzZXJfbmFtZSI6IlNLQ0MuMDc3NjZAc2suY29tIiwiZGlzcGxheU5hbWUiOiLsoJXsirkqKiIsInNjb3BlIjpbImNsaWVudCJdLCJ3b3Jrc3BhY2VzIjp7InN0YXRpb25Xb3Jrc3BhY2VzIjpudWxsLCJzcXVhcmVXb3Jrc3BhY2VzIjpudWxsLCJwYXZpbGlvbldvcmtzcGFjZXMiOm51bGwsImNpbmVyb29tV29ya3NwYWNlcyI6W3siaWQiOiJuZTEtbTItYzIiLCJuYW1lIjoiU0sgVW5pdmVyc2l0eSIsInRlbmFudElkIjoicjM2eC1yQG5lMS1tMi1jMiIsInJvbGVzIjpbIlVzZXIiXX0seyJpZCI6Im5lMS1tMi1jMTciLCJuYW1lIjoiU0so7KO8KUMmQyIsInRlbmFudElkIjoicjM2eC1yQG5lMS1tMi1jMTciLCJyb2xlcyI6WyJVc2VyIl19XSwic3R1ZGlvV29ya3NwYWNlIjpudWxsfSwiZXhwIjoxNjAxNDMwMDgzLCJhdXRob3JpdGllcyI6WyJVc2VyIl0sImp0aSI6IjQ4NWFhZDljLTI4ZmYtNDgzZS1hY2YxLWVhOTU5OTU0NmUxYyIsImNsaWVudF9pZCI6Im5hcmEifQ.u8XB7gjZyQxheQdu4SJe3vu3_lyiiBrH96B_ApFgePk



### Create Menu
POST http://localhost:8080/773613/menus
audienceId: r36x-r@ne1-m2-c2
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhZGRpdGlvbmFsSW5mb3JtYXRpb24iOnsiY29tcGFueUNvZGUiOiJTS0NDIiwiZW1wbG95ZWVJZCI6IjA3NzY2In0sImxvZ2luSWQiOiJTS0NDLjA3NzY2QHNrLmNvbSIsInVzZXJfbmFtZSI6IlNLQ0MuMDc3NjZAc2suY29tIiwiZGlzcGxheU5hbWUiOiLsoJXsirkqKiIsInNjb3BlIjpbImNsaWVudCJdLCJ3b3Jrc3BhY2VzIjp7InN0YXRpb25Xb3Jrc3BhY2VzIjpudWxsLCJzcXVhcmVXb3Jrc3BhY2VzIjpudWxsLCJwYXZpbGlvbldvcmtzcGFjZXMiOm51bGwsImNpbmVyb29tV29ya3NwYWNlcyI6W3siaWQiOiJuZTEtbTItYzIiLCJuYW1lIjoiU0sgVW5pdmVyc2l0eSIsInRlbmFudElkIjoicjM2eC1yQG5lMS1tMi1jMiIsInJvbGVzIjpbIlVzZXIiXX0seyJpZCI6Im5lMS1tMi1jMTciLCJuYW1lIjoiU0so7KO8KUMmQyIsInRlbmFudElkIjoicjM2eC1yQG5lMS1tMi1jMTciLCJyb2xlcyI6WyJVc2VyIl19XSwic3R1ZGlvV29ya3NwYWNlIjpudWxsfSwiZXhwIjoxNjAxNDMwMDgzLCJhdXRob3JpdGllcyI6WyJVc2VyIl0sImp0aSI6IjQ4NWFhZDljLTI4ZmYtNDgzZS1hY2YxLWVhOTU5OTU0NmUxYyIsImNsaWVudF9pZCI6Im5hcmEifQ.u8XB7gjZyQxheQdu4SJe3vu3_lyiiBrH96B_ApFgePk
content-type: application/json

{"type":"CATEGORY","name":"카테고리3","order":2,"accessType":"COMMUNITY_ALL_MEMBER"}

### Edit Menu
PUT http://localhost:8080/773613/menus/e89ff4ae-d006-4345-960a-a35ce2ec628a
audienceId: r36x-r@ne1-m2-c2
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhZGRpdGlvbmFsSW5mb3JtYXRpb24iOnsiY29tcGFueUNvZGUiOiJTS0NDIiwiZW1wbG95ZWVJZCI6IjA3NzY2In0sImxvZ2luSWQiOiJTS0NDLjA3NzY2QHNrLmNvbSIsInVzZXJfbmFtZSI6IlNLQ0MuMDc3NjZAc2suY29tIiwiZGlzcGxheU5hbWUiOiLsoJXsirkqKiIsInNjb3BlIjpbImNsaWVudCJdLCJ3b3Jrc3BhY2VzIjp7InN0YXRpb25Xb3Jrc3BhY2VzIjpudWxsLCJzcXVhcmVXb3Jrc3BhY2VzIjpudWxsLCJwYXZpbGlvbldvcmtzcGFjZXMiOm51bGwsImNpbmVyb29tV29ya3NwYWNlcyI6W3siaWQiOiJuZTEtbTItYzIiLCJuYW1lIjoiU0sgVW5pdmVyc2l0eSIsInRlbmFudElkIjoicjM2eC1yQG5lMS1tMi1jMiIsInJvbGVzIjpbIlVzZXIiXX0seyJpZCI6Im5lMS1tMi1jMTciLCJuYW1lIjoiU0so7KO8KUMmQyIsInRlbmFudElkIjoicjM2eC1yQG5lMS1tMi1jMTciLCJyb2xlcyI6WyJVc2VyIl19XSwic3R1ZGlvV29ya3NwYWNlIjpudWxsfSwiZXhwIjoxNjAxNDMwMDgzLCJhdXRob3JpdGllcyI6WyJVc2VyIl0sImp0aSI6IjQ4NWFhZDljLTI4ZmYtNDgzZS1hY2YxLWVhOTU5OTU0NmUxYyIsImNsaWVudF9pZCI6Im5hcmEifQ.u8XB7gjZyQxheQdu4SJe3vu3_lyiiBrH96B_ApFgePk
content-type: application/json

{"nameValues":[{"name":"name","value":"카테고리123"}]}



