apiVersion: v1
kind: Service
metadata:
  name: manager-front-service
spec:
  ports:
    - name: '80'
      port: 80
      targetPort: 80
  selector:
    app: manager-front
  type: ClusterIP
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: manager-front-virtualservice
spec:
  hosts:
    - 'stg-star.mysuni.sk.com'
    - 'ma-star.mysuni.sk.com'
    - 'star.mysuni.sk.com'
    - 'university.sk.com'
  gateways:
    - skuniv-gateway
  http:
    - match:
        - uri:
            exact: /
      route:
        - destination:
            host: manager-front-service
            port:
              number: 80
    - match:
        - uri:
            prefix: /manager
      route:
        - destination:
            host: manager-front-service
            port:
              number: 80
